#!/bin/bash

repo init -u https://github.com/AxionAOSP/android.git -b lineage-23.0 --git-lfs
/opt/crave/resync.sh

git clone https://github.com/CharaDreemurrDT/axionaosp_device_motorola_guam.git -b lineage-23.0 device/motorola/guam
git clone https://github.com/LineageOS/android_device_motorola_sm6225-common.git -b lineage-23.0 device/motorola/sm6225-common
git clone https://github.com/CharaDreemurrDT/ksun_kernel_motorola_sm6225.git kernel/motorola/sm6225
git clone https://github.com/TheMuppets/proprietary_vendor_motorola_sm6225-common.git -b lineage-23.0 vendor/motorola/sm6225-common
git clone https://github.com/TheMuppets/proprietary_vendor_motorola_guam.git -b lineage-23.0 vendor/motorola/guam
git clone https://github.com/LineageOS/android_hardware_motorola.git -b lineage-23.0 hardware/motorola

rm -rf out/target

. build/env*

export BUILD_USERNAME=chara
export TZ=America/Recife

axion guam userdebug vanilla
ax -br
