#!/bin/bash

repo init -u https://github.com/AxionAOSP/android.git -b lineage-23.1 --git-lfs
/opt/crave/resync.sh

git clone https://github.com/CharaDreemurrDT/axionaosp_device_motorola_guam.git -b lineage-23.1 device/motorola/guam
git clone https://github.com/LineageOS/android_device_motorola_sm6225-common.git -b lineage-23.1 device/motorola/sm6225-common
git clone https://github.com/CharaDreemurrDT/ksun_kernel_motorola_sm6225.git kernel/motorola/sm6225 -b axionaosp
git clone https://github.com/TheMuppets/proprietary_vendor_motorola_sm6225-common.git -b lineage-23.1 vendor/motorola/sm6225-common
git clone https://github.com/TheMuppets/proprietary_vendor_motorola_guam.git -b lineage-23.1 vendor/motorola/guam
git clone https://github.com/LineageOS/android_hardware_motorola.git -b lineage-23.1 hardware/motorola

rm -rf out/target

. build/env*

export BUILD_USERNAME=chara
export TZ=America/Recife
cd kernel/motorola/sm6225
rm -rf KernelSU-Next
rm -rf drivers/kernelsu
curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy
cd ../../..
axion guam userdebug vanilla
ax -br
