#!/bin/bash

repo init -u https://github.com/Lunaris-AOSP/android -b 16 --git-lfs
/opt/crave/resync.sh

git clone https://github.com/CharaDreemurrDT/android_device_xiaomi_tanzanite -b lunaris device/xiaomi/tanzanite
git clone https://github.com/CharaDreemurrDT/android_device_xiaomi_tanzanite-kernel -b grayraven device/xiaomi/tanzanite-kernel
git clone https://github.com/nathanzerogarage/proprietary_vendor_xiaomi_tanzanite -b lineage-23.1 vendor/xiaomi/tanzanite
git clone https://github.com/TogoFire/packages_apps_ViPER4AndroidFX.git -b v4a packages/apps/ViPER4AndroidFX
git clone https://github.com/nathanzerogarage/android_hardware_xiaomi -b lineage-23.1 hardware/xiaomi
git clone https://github.com/nathanzerogarage/android_hardware_mediatek -b lineage-23.1 hardware/mediatek
git clone https://github.com/nathanzerogarage/android_device_mediatek_sepolicy_vndr -b lineage-23.1 device/mediatek/sepolicy_vndr
git clone https://github.com/MillenniumOSS/android_vendor_mediatek_ims.git -b sixteen vendor/mediatek/ims

rm -rf out/target

. build/env*

export BUILD_USERNAME=chara
export TZ=America/Recife

lunch lineage_tanzanite-bp2a-user
m lunaris
