#!/bin/bash

repo init -u https://github.com/crdroidandroid/android.git -b 16.0 --git-lfs --no-clone-bundle
/opt/crave/resync.sh

rm -rf device/xiaomi/tanzanite
rm -rf device/xiaomi/tanzanite-kernel
rm -rf vendor/xiaomi/tanzanite
rm -rf packages/apps/ViPER4AndroidFX
rm -rf hardware/xiaomi
rm -rf hardware/mediatek
rm -rf device/mediatek/sepolicy_vndr
rm -rf vendor/mediatek/ims

git clone https://github.com/nathanzerogarage/android_device_xiaomi_tanzanite -b lineage-23.2 device/xiaomi/tanzanite
git clone https://github.com/nathanzerogarage/android_device_xiaomi_tanzanite-kernel -b vanilla device/xiaomi/tanzanite-kernel
git clone https://github.com/nathanzerogarage/proprietary_vendor_xiaomi_tanzanite -b sixteen-qpr2 vendor/xiaomi/tanzanite
git clone https://github.com/TogoFire/packages_apps_ViPER4AndroidFX.git -b v4a packages/apps/ViPER4AndroidFX
git clone https://github.com/nathanzerogarage/android_hardware_xiaomi -b lineage-23.1 hardware/xiaomi
git clone https://github.com/nathanzerogarage/android_hardware_mediatek -b lineage-23.1 hardware/mediatek
git clone https://github.com/nathanzerogarage/android_device_mediatek_sepolicy_vndr -b lineage-23.2 device/mediatek/sepolicy_vndr
git clone https://github.com/MillenniumOSS/android_vendor_mediatek_ims.git -b sixteen-qpr2 vendor/mediatek/ims

wget https://raw.githubusercontent.com/iamCloverDT/crDroid-build-signed-script/refs/heads/16.0/create-signed-env.sh
chmod +x create-signed-env.sh
./create-signed-env.sh

cd external/wpa_supplicant_8
wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/do_not_set_NL80211_WPA_VERSION_3.patch
patch -p1 < do_not_set_NL80211_WPA_VERSION_3.patch

cd ../..
cd packages/apps/Aperture
wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/01-aperture-mtk-hfps-mode.patch
patch -p1 < 01-aperture-mtk-hfps-mode.patch

rm -rf out/target

. build/env*

export BUILD_USERNAME=chara
export TZ=America/Recife

brunch tanzanite userdebug
