#!/bin/bash

repo init -u https://github.com/LineageOS/android.git -b lineage-22.2 --git-lfs --no-clone-bundle
/opt/crave/resync.sh

# Delete previous sources
echo "Deleting previous sources..."
rm -rf device/xiaomi/tanzanite
rm -rf device/xiaomi/tanzanite-kernel
rm -rf vendor/xiaomi/tanzanite
rm -rf packages/apps/ViPER4AndroidFX
rm -rf hardware/xiaomi
rm -rf hardware/mediatek
rm -rf device/mediatek/sepolicy_vndr
rm -rf vendor/mediatek/ims
# rm -rf vendor/*priv*
rm -rf vendor/lineage-priv/keys

# Device source
git clone https://github.com/iamCloverDT/android_device_xiaomi_tanzanite -b lineage-22.2 device/xiaomi/tanzanite
# Prebuilt kernel source
git clone https://github.com/nathanzerogarage/android_device_xiaomi_tanzanite-kernel -b vanilla device/xiaomi/tanzanite-kernel
# Vendor source
git clone https://github.com/nathanzerogarage/proprietary_vendor_xiaomi_tanzanite -b fifteen vendor/xiaomi/tanzanite
# ViPER4AndroidFX sources
git clone https://github.com/TogoFire/packages_apps_ViPER4AndroidFX.git -b v4a packages/apps/ViPER4AndroidFX
# Hardware sources
git clone https://github.com/aerichandesu0011/android_hardware_xiaomi -b lineage-22.2 hardware/xiaomi
git clone https://github.com/aerichandesu0011/android_hardware_mediatek -b lineage-22.2 hardware/mediatek
git clone https://github.com/aerichandesu0011/android_device_mediatek_sepolicy_vndr -b lineage-22.2 device/mediatek/sepolicy_vndr
git clone https://github.com/MillenniumOSS/android_vendor_mediatek_ims.git -b sixteen-qpr2 vendor/mediatek/ims

# Create signing keys
subject='/C=BR/ST=Pernambuco/L=Petrolina/O=Starlight/OU=AndroidKernel/CN=Android/emailAddress=clover@tutamail.com'
mkdir ~/.android-certs
for x in releasekey platform shared media networkstack testkey bluetooth sdk_sandbox verifiedboot nfc; do \
    ./development/tools/make_key ~/.android-certs/$x "$subject"; \
done
mkdir vendor/lineage-priv
mv ~/.android-certs vendor/lineage-priv/keys
echo "PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/lineage-priv/keys/releasekey" > vendor/lineage-priv/keys/keys.mk
pushd vendor/lineage-priv/keys
wget https://raw.githubusercontent.com/iamCloverDT/personal-build-tools/refs/heads/main/signing/BUILD.bazel
popd

# pushd external/wpa_supplicant_8
# wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/do_not_set_NL80211_WPA_VERSION_3.patch
# patch -p1 < do_not_set_NL80211_WPA_VERSION_3.patch
# popd

# pushd packages/apps/Aperture
# wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/01-aperture-mtk-hfps-mode.patch
# patch -p1 < 01-aperture-mtk-hfps-mode.patch
# popd

rm -rf out/target

. build/envsetup.sh

export BUILD_HOSTNAME=crave
export BUILD_USERNAME=clover
export TZ=America/Recife
# Lunch target selection
echo "Selecting target with lunch.."
lunch lineage_tanzanite-bp1a-userdebug
echo "Lunch target selected."
# Building the ROM
echo "========================="
echo "Starting ROM Compilation..."
echo "========================="
mka bacon
