#!/bin/bash

repo init -u https://github.com/crdroidandroid/android.git -b lineage-22.2 --git-lfs --no-clone-bundle
/opt/crave/resync.sh

# Delete previous sources
echo "Deleting previous sources..."
rm -rf device/xiaomi/tanzanite
rm -rf device/xiaomi/tanzanite-kernel
rm -rf vendor/xiaomi/tanzanite
rm -rf packages/apps/ViPER4AndroidFX
rm -rf hardware/xiaomi
rm -rf hardware/mediatek
rm -rf device/mediatek/sepolicy_vndr
rm -rf vendor/mediatek/ims
# rm -rf vendor/*priv*
rm -rf vendor/lineage-priv/keys

# Device source
git clone https://github.com/iamCloverDT/android_device_xiaomi_tanzanite -b lineage-23.2 device/xiaomi/tanzanite
# Prebuilt kernel source
git clone https://github.com/iamCloverDT/android_device_xiaomi_tanzanite-kernel -b ksu device/xiaomi/tanzanite-kernel
# Vendor source
git clone https://github.com/nathanzerogarage/proprietary_vendor_xiaomi_tanzanite -b sixteen-qpr2 vendor/xiaomi/tanzanite
# ViPER4AndroidFX sources
git clone https://github.com/TogoFire/packages_apps_ViPER4AndroidFX.git -b v4a packages/apps/ViPER4AndroidFX
# Hardware sources
git clone https://github.com/nathanzerogarage/android_hardware_xiaomi -b lineage-23.2 hardware/xiaomi
git clone https://github.com/nathanzerogarage/android_hardware_mediatek -b lineage-23.2 hardware/mediatek
git clone https://github.com/nathanzerogarage/android_device_mediatek_sepolicy_vndr -b lineage-23.2 device/mediatek/sepolicy_vndr
git clone https://github.com/MillenniumOSS/android_vendor_mediatek_ims.git -b sixteen-qpr2 vendor/mediatek/ims

echo "Patching wpa_supplicant_8..."
pushd external/wpa_supplicant_8
wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/do_not_set_NL80211_WPA_VERSION_3.patch
patch -p1 < do_not_set_NL80211_WPA_VERSION_3.patch
popd
echo "wpa_supplicant_8 was patched."

echo "Patching Apeture..."
pushd packages/apps/Aperture
wget https://raw.githubusercontent.com/nathanzerogarage/patches/refs/heads/main/01-aperture-mtk-hfps-mode.patch
patch -p1 < 01-aperture-mtk-hfps-mode.patch
popd
echo "Aperture was patched."

rm -rf out

. build/envsetup.sh

export BUILD_HOSTNAME=crave
export BUILD_USERNAME=clover
export TZ=America/Recife
# Building the ROM
echo "--------------------------"
echo "Starting ROM compilation.."
echo "--------------------------"
brunch tanzanite
